# Generated by Django 3.0.5 on 2021-03-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='H4803E4ZWNWMI0MZX8TDTSOKQVQNQN', max_length=30, null=True, verbose_name='confirmation code'),
        ),
    ]
